# redisson.yml --- 存放于application.yml同级目录
singleServerConfig:
  #  连接空闲超时，单位：毫秒
  idleConnectionTimeout: 100000
  #  连接超时，单位：毫秒
  connectTimeout: 10000
  #  命令等待超时，单位：毫秒
  timeout: 3000
  #  命令失败重试次数
  retryAttempts: 3
  #  命令重试发送时间间隔，单位：毫秒
  retryInterval: 1500
  #  密码
  password: password
  #  单个连接最大订阅数量
  subscriptionsPerConnection: 5
  #  客户端名称
  clientName: null
  #  节点地址
  address: redis://localhost:6379
  #  发布和订阅连接的最小空闲连接数
  subscriptionConnectionMinimumIdleSize: 1
  #  发布和订阅连接池大小
  subscriptionConnectionPoolSize: 50
  #  最小空闲连接数
  connectionMinimumIdleSize: 32
  #  连接池大小
  connectionPoolSize: 64
  #  redis数据库编号
  database: 12
  #  DNS监测时间间隔，单位：毫秒
  dnsMonitoringInterval: 5000
#  线程池数量
threads: 0
#  Netty线程池数量
nettyThreads: 0
#  编码
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
#  传输模式
transportMode: "NIO"
#  配置看门狗的默认超时时间为30s，这里改为10s
lockWatchdogTimeout: 10000
